=begin
#GeoSearch

#Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

The version of the OpenAPI document: 1.3.2
Contact: info@geosearch.dev
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'spec_helper'
require 'json'

# Unit tests for GeoSearch::CountriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CountriesApi' do
  before do
    # run before each test
    @api_instance = GeoSearch::CountriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CountriesApi' do
    it 'should create an instance of CountriesApi' do
      expect(@api_instance).to be_instance_of(GeoSearch::CountriesApi)
    end
  end

  # unit tests for country_neighbors
  # List neighboring countries
  # Returns countries that share a border with the specified country.
  # @param code ISO alpha-2 country code
  # @param [Hash] opts the optional parameters
  # @option opts [String] :lang ISO 639-1 language code for localized names (e.g., de, fr, ja)
  # @option opts [String] :fields Comma-separated list of fields to include in the response
  # @return [CountryListResponse]
  describe 'country_neighbors test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_country
  # Get country by ISO code
  # Returns a single country by its ISO alpha-2 code.
  # @param code ISO alpha-2 country code
  # @param [Hash] opts the optional parameters
  # @option opts [String] :lang ISO 639-1 language code for localized names (e.g., de, fr, ja)
  # @option opts [String] :fields Comma-separated list of fields to include in the response
  # @return [CountrySingleResponse]
  describe 'get_country test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_countries
  # List countries
  # Returns a paginated list of countries with optional filtering and sorting.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :lang ISO 639-1 language code for localized names (e.g., de, fr, ja)
  # @option opts [String] :continent Filter by continent code (AF, AN, AS, EU, NA, OC, SA)
  # @option opts [String] :iso_code Filter by ISO alpha-2 codes (comma-separated)
  # @option opts [Integer] :population_min Minimum population filter
  # @option opts [Integer] :population_max Maximum population filter
  # @option opts [String] :cursor Pagination cursor from a previous response
  # @option opts [Integer] :limit Number of results per page (1-100, default 25)
  # @option opts [String] :fields Comma-separated list of fields to include in the response
  # @option opts [String] :sort Sort field and direction. Allowed: name, population, area_sq_km. Prefix with - for descending.
  # @return [CountryListResponse]
  describe 'list_countries test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_country_regions
  # List regions in a country
  # Returns a paginated list of regions (administrative divisions) within a country.
  # @param code ISO alpha-2 country code
  # @param [Hash] opts the optional parameters
  # @option opts [String] :lang ISO 639-1 language code for localized names (e.g., de, fr, ja)
  # @option opts [String] :cursor Pagination cursor from a previous response
  # @option opts [Integer] :limit Number of results per page (1-100, default 25)
  # @option opts [String] :fields Comma-separated list of fields to include in the response
  # @option opts [String] :sort Sort field. Allowed: name, population.
  # @return [RegionListResponse]
  describe 'list_country_regions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
