=begin
#GeoSearch

#Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

The version of the OpenAPI document: 1.3.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'cgi'

module GeoSearch
  class PostalCodesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # List postal codes
    # Returns a paginated list of postal codes with optional filtering by country and code.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :lang ISO 639-1 language code for localized names (e.g., de, fr, ja)
    # @option opts [String] :country Filter by ISO alpha-2 country codes (comma-separated)
    # @option opts [String] :code Filter by postal code
    # @option opts [Integer] :within Return only results whose coordinates fall geometrically inside the boundary of the given area, identified by its GeoNames id. Countries and administrative regions are valid areas; a city id is not.  Accepts exactly one id. A COMMA-SEPARATED LIST IS REJECTED with a 422 naming the limit — a deliberate departure from the comma-separated convention &#x60;country&#x60; uses, because each value would be a separate polygon intersection. Ask for one area per request.  COST: a request using this parameter consumes 2 quota units instead of 1, on every plan including Free. Combining it with &#x60;bbox&#x60; still costs 2, not 3 — the highest multiplier applies rather than the sum, and adding a box makes the query cheaper to serve, so it is never penalised.  This asks a GEOMETRIC question and can therefore return a different set of cities than &#x60;/v1/regions/{id}/cities&#x60;, which asks an administrative one. See that endpoint&#39;s description for when and why the two disagree.  Two failures are reported with distinct 400 codes so a typo is distinguishable from a coverage gap: &#x60;area_not_an_area&#x60; means the id does not name a country or region at all, and &#x60;area_no_boundary&#x60; means it does but no boundary polygon is available for it yet.
    # @option opts [String] :bbox Return only results inside the bounding box, given as four comma-separated numbers in the order &#x60;w,s,e,n&#x60; — west longitude, south latitude, east longitude, north latitude.  Longitudes must be within [-180, 180] and latitudes within [-90, 90].  A box where WEST IS GREATER THAN EAST wraps the antimeridian and is fully supported: &#x60;bbox&#x3D;170,-20,-170,-10&#x60; is a box around Fiji, evaluated as the union of the two halves it spans. Latitude has no equivalent wrap-around meaning, so &#x60;s&#x60; greater than &#x60;n&#x60; is a validation error rather than a wrapped box.  Charged at the standard request cost of 1 unit. Adding it to a &#x60;within&#x60; query narrows the candidate set before the polygon test and does not raise the charge.
    # @option opts [String] :cursor Pagination cursor from a previous response
    # @option opts [Integer] :limit Number of results per page (1-100, default 25) (default to 25)
    # @option opts [String] :fields Comma-separated list of fields to include in the response
    # @option opts [String] :sort Sort field. Allowed: postal_code, country_code, place_name, id.
    # @return [PostalCodeListResponse]
    def list_postal_codes(opts = {})
      data, _status_code, _headers = list_postal_codes_with_http_info(opts)
      data
    end

    # List postal codes
    # Returns a paginated list of postal codes with optional filtering by country and code.
    # @param [Hash] opts the optional parameters
    # @option opts [String] :lang ISO 639-1 language code for localized names (e.g., de, fr, ja)
    # @option opts [String] :country Filter by ISO alpha-2 country codes (comma-separated)
    # @option opts [String] :code Filter by postal code
    # @option opts [Integer] :within Return only results whose coordinates fall geometrically inside the boundary of the given area, identified by its GeoNames id. Countries and administrative regions are valid areas; a city id is not.  Accepts exactly one id. A COMMA-SEPARATED LIST IS REJECTED with a 422 naming the limit — a deliberate departure from the comma-separated convention &#x60;country&#x60; uses, because each value would be a separate polygon intersection. Ask for one area per request.  COST: a request using this parameter consumes 2 quota units instead of 1, on every plan including Free. Combining it with &#x60;bbox&#x60; still costs 2, not 3 — the highest multiplier applies rather than the sum, and adding a box makes the query cheaper to serve, so it is never penalised.  This asks a GEOMETRIC question and can therefore return a different set of cities than &#x60;/v1/regions/{id}/cities&#x60;, which asks an administrative one. See that endpoint&#39;s description for when and why the two disagree.  Two failures are reported with distinct 400 codes so a typo is distinguishable from a coverage gap: &#x60;area_not_an_area&#x60; means the id does not name a country or region at all, and &#x60;area_no_boundary&#x60; means it does but no boundary polygon is available for it yet.
    # @option opts [String] :bbox Return only results inside the bounding box, given as four comma-separated numbers in the order &#x60;w,s,e,n&#x60; — west longitude, south latitude, east longitude, north latitude.  Longitudes must be within [-180, 180] and latitudes within [-90, 90].  A box where WEST IS GREATER THAN EAST wraps the antimeridian and is fully supported: &#x60;bbox&#x3D;170,-20,-170,-10&#x60; is a box around Fiji, evaluated as the union of the two halves it spans. Latitude has no equivalent wrap-around meaning, so &#x60;s&#x60; greater than &#x60;n&#x60; is a validation error rather than a wrapped box.  Charged at the standard request cost of 1 unit. Adding it to a &#x60;within&#x60; query narrows the candidate set before the polygon test and does not raise the charge.
    # @option opts [String] :cursor Pagination cursor from a previous response
    # @option opts [Integer] :limit Number of results per page (1-100, default 25) (default to 25)
    # @option opts [String] :fields Comma-separated list of fields to include in the response
    # @option opts [String] :sort Sort field. Allowed: postal_code, country_code, place_name, id.
    # @return [Array<(PostalCodeListResponse, Integer, Hash)>] PostalCodeListResponse data, response status code and response headers
    def list_postal_codes_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: PostalCodesApi.list_postal_codes ...'
      end
      if @api_client.config.client_side_validation && !opts[:'lang'].nil? && opts[:'lang'].to_s.length > 5
        fail ArgumentError, 'invalid value for "opts[:"lang"]" when calling PostalCodesApi.list_postal_codes, the character length must be smaller than or equal to 5.'
      end

      if @api_client.config.client_side_validation && !opts[:'lang'].nil? && opts[:'lang'].to_s.length < 2
        fail ArgumentError, 'invalid value for "opts[:"lang"]" when calling PostalCodesApi.list_postal_codes, the character length must be greater than or equal to 2.'
      end

      pattern = Regexp.new(/^-?\d+(\.\d+)?(,-?\d+(\.\d+)?){3}$/)
      if @api_client.config.client_side_validation && !opts[:'bbox'].nil? && opts[:'bbox'] !~ pattern
        fail ArgumentError, "invalid value for 'opts[:\"bbox\"]' when calling PostalCodesApi.list_postal_codes, must conform to the pattern #{pattern}."
      end

      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] > 100
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling PostalCodesApi.list_postal_codes, must be smaller than or equal to 100.'
      end

      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] < 1
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling PostalCodesApi.list_postal_codes, must be greater than or equal to 1.'
      end

      # resource path
      local_var_path = '/v1/postal-codes'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'lang'] = opts[:'lang'] if !opts[:'lang'].nil?
      query_params[:'country'] = opts[:'country'] if !opts[:'country'].nil?
      query_params[:'code'] = opts[:'code'] if !opts[:'code'].nil?
      query_params[:'within'] = opts[:'within'] if !opts[:'within'].nil?
      query_params[:'bbox'] = opts[:'bbox'] if !opts[:'bbox'].nil?
      query_params[:'cursor'] = opts[:'cursor'] if !opts[:'cursor'].nil?
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?
      query_params[:'fields'] = opts[:'fields'] if !opts[:'fields'].nil?
      query_params[:'sort'] = opts[:'sort'] if !opts[:'sort'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'PostalCodeListResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKeyAuth']

      new_options = opts.merge(
        :operation => :"PostalCodesApi.list_postal_codes",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PostalCodesApi#list_postal_codes\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Find nearest postal codes
    # Returns the nearest postal codes to a given latitude/longitude using PostGIS spatial index.
    # @param lat [Float] Latitude (-90 to 90)
    # @param lon [Float] Longitude (-180 to 180)
    # @param [Hash] opts the optional parameters
    # @option opts [String] :lang ISO 639-1 language code for localized names (e.g., de, fr, ja)
    # @option opts [Integer] :limit Number of results (1-10, default 1) (default to 1)
    # @return [PostalCodeListResponse]
    def nearest_postal_code(lat, lon, opts = {})
      data, _status_code, _headers = nearest_postal_code_with_http_info(lat, lon, opts)
      data
    end

    # Find nearest postal codes
    # Returns the nearest postal codes to a given latitude/longitude using PostGIS spatial index.
    # @param lat [Float] Latitude (-90 to 90)
    # @param lon [Float] Longitude (-180 to 180)
    # @param [Hash] opts the optional parameters
    # @option opts [String] :lang ISO 639-1 language code for localized names (e.g., de, fr, ja)
    # @option opts [Integer] :limit Number of results (1-10, default 1) (default to 1)
    # @return [Array<(PostalCodeListResponse, Integer, Hash)>] PostalCodeListResponse data, response status code and response headers
    def nearest_postal_code_with_http_info(lat, lon, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: PostalCodesApi.nearest_postal_code ...'
      end
      # verify the required parameter 'lat' is set
      if @api_client.config.client_side_validation && lat.nil?
        fail ArgumentError, "Missing the required parameter 'lat' when calling PostalCodesApi.nearest_postal_code"
      end
      if @api_client.config.client_side_validation && lat > 90
        fail ArgumentError, 'invalid value for "lat" when calling PostalCodesApi.nearest_postal_code, must be smaller than or equal to 90.'
      end

      if @api_client.config.client_side_validation && lat < -90
        fail ArgumentError, 'invalid value for "lat" when calling PostalCodesApi.nearest_postal_code, must be greater than or equal to -90.'
      end

      # verify the required parameter 'lon' is set
      if @api_client.config.client_side_validation && lon.nil?
        fail ArgumentError, "Missing the required parameter 'lon' when calling PostalCodesApi.nearest_postal_code"
      end
      if @api_client.config.client_side_validation && lon > 180
        fail ArgumentError, 'invalid value for "lon" when calling PostalCodesApi.nearest_postal_code, must be smaller than or equal to 180.'
      end

      if @api_client.config.client_side_validation && lon < -180
        fail ArgumentError, 'invalid value for "lon" when calling PostalCodesApi.nearest_postal_code, must be greater than or equal to -180.'
      end

      if @api_client.config.client_side_validation && !opts[:'lang'].nil? && opts[:'lang'].to_s.length > 5
        fail ArgumentError, 'invalid value for "opts[:"lang"]" when calling PostalCodesApi.nearest_postal_code, the character length must be smaller than or equal to 5.'
      end

      if @api_client.config.client_side_validation && !opts[:'lang'].nil? && opts[:'lang'].to_s.length < 2
        fail ArgumentError, 'invalid value for "opts[:"lang"]" when calling PostalCodesApi.nearest_postal_code, the character length must be greater than or equal to 2.'
      end

      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] > 10
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling PostalCodesApi.nearest_postal_code, must be smaller than or equal to 10.'
      end

      if @api_client.config.client_side_validation && !opts[:'limit'].nil? && opts[:'limit'] < 1
        fail ArgumentError, 'invalid value for "opts[:"limit"]" when calling PostalCodesApi.nearest_postal_code, must be greater than or equal to 1.'
      end

      # resource path
      local_var_path = '/v1/postal-codes/nearest'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'lat'] = lat
      query_params[:'lon'] = lon
      query_params[:'lang'] = opts[:'lang'] if !opts[:'lang'].nil?
      query_params[:'limit'] = opts[:'limit'] if !opts[:'limit'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'PostalCodeListResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['apiKeyAuth']

      new_options = opts.merge(
        :operation => :"PostalCodesApi.nearest_postal_code",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: PostalCodesApi#nearest_postal_code\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
