=begin
#GeoAPI

#Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

The version of the OpenAPI document: 1.2.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

# Common files
require 'geoapi/api_client'
require 'geoapi/api_error'
require 'geoapi/api_model_base'
require 'geoapi/version'
require 'geoapi/configuration'

# Models
require 'geoapi/models/autocomplete_list_response'
require 'geoapi/models/autocomplete_result'
require 'geoapi/models/batch_request'
require 'geoapi/models/boundary'
require 'geoapi/models/boundary_single_response'
require 'geoapi/models/city'
require 'geoapi/models/city_list_response'
require 'geoapi/models/city_single_response'
require 'geoapi/models/country'
require 'geoapi/models/country_list_response'
require 'geoapi/models/country_ref'
require 'geoapi/models/country_single_response'
require 'geoapi/models/error_response'
require 'geoapi/models/error_response_error'
require 'geoapi/models/error_response_error_details_inner'
require 'geoapi/models/geo_json_geometry'
require 'geoapi/models/geo_json_multi_polygon'
require 'geoapi/models/get_status200_response'
require 'geoapi/models/get_status200_response_data'
require 'geoapi/models/hierarchy_list_response'
require 'geoapi/models/hierarchy_node'
require 'geoapi/models/ip_result'
require 'geoapi/models/ip_result_city'
require 'geoapi/models/ip_result_continent'
require 'geoapi/models/ip_result_country'
require 'geoapi/models/ip_result_location'
require 'geoapi/models/ip_result_postal'
require 'geoapi/models/ip_result_region'
require 'geoapi/models/ip_single_response'
require 'geoapi/models/nearby_city'
require 'geoapi/models/nearby_city_list_response'
require 'geoapi/models/pagination_meta'
require 'geoapi/models/postal_code'
require 'geoapi/models/postal_code_list_response'
require 'geoapi/models/quota_detail'
require 'geoapi/models/region'
require 'geoapi/models/region_list_response'
require 'geoapi/models/region_ref'
require 'geoapi/models/region_single_response'
require 'geoapi/models/reverse_geocode_result'
require 'geoapi/models/reverse_geocode_single_response'
require 'geoapi/models/search_list_response'
require 'geoapi/models/search_result'
require 'geoapi/models/timezone'
require 'geoapi/models/timezone_list_response'
require 'geoapi/models/timezone_single_response'
require 'geoapi/models/upgrade_detail'

# APIs
require 'geoapi/api/batch_api'
require 'geoapi/api/boundaries_api'
require 'geoapi/api/cities_api'
require 'geoapi/api/countries_api'
require 'geoapi/api/health_api'
require 'geoapi/api/ip_geolocation_api'
require 'geoapi/api/postal_codes_api'
require 'geoapi/api/regions_api'
require 'geoapi/api/search_api'
require 'geoapi/api/timezones_api'

module GeoAPI
  class << self
    # Customize default settings for the SDK using block.
    #   GeoAPI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
