=begin
#GeoSearch

#Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, and timezones through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

The version of the OpenAPI document: 1.3.3
Contact: info@geosearch.dev
Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module GeoSearch
  class Region < ApiModelBase
    attr_accessor :id

    attr_accessor :geoname_id

    attr_accessor :country_code

    attr_accessor :admin_code

    attr_accessor :name

    attr_accessor :ascii_name

    attr_accessor :level

    attr_accessor :parent_geoname_id

    attr_accessor :population

    attr_accessor :latitude

    attr_accessor :longitude

    attr_accessor :country

    # Region boundary. Returned by default on `GET /v1/regions/{id}`, and on request via `?fields=geometry` on `GET /v1/regions` and `GET /v1/countries/{code}/regions`.  REQUIRES A PAID PLAN. On all three of those routes this key is OMITTED ENTIRELY for a Free-tier key — absent, not null, with a 200 status and no error. A client reading `data.geometry.type` unconditionally will fail on a null dereference.  To be told explicitly rather than silently, request the polygon from `GET /v1/boundaries/{geoname_id}`, which answers a Free key with a 403 and an upgrade link.
    attr_accessor :geometry

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'geoname_id' => :'geoname_id',
        :'country_code' => :'country_code',
        :'admin_code' => :'admin_code',
        :'name' => :'name',
        :'ascii_name' => :'ascii_name',
        :'level' => :'level',
        :'parent_geoname_id' => :'parent_geoname_id',
        :'population' => :'population',
        :'latitude' => :'latitude',
        :'longitude' => :'longitude',
        :'country' => :'country',
        :'geometry' => :'geometry'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'geoname_id' => :'Integer',
        :'country_code' => :'String',
        :'admin_code' => :'String',
        :'name' => :'String',
        :'ascii_name' => :'String',
        :'level' => :'Integer',
        :'parent_geoname_id' => :'Integer',
        :'population' => :'Integer',
        :'latitude' => :'Float',
        :'longitude' => :'Float',
        :'country' => :'CountryRef',
        :'geometry' => :'GeoJSONMultiPolygon'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `GeoSearch::Region` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `GeoSearch::Region`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'geoname_id')
        self.geoname_id = attributes[:'geoname_id']
      end

      if attributes.key?(:'country_code')
        self.country_code = attributes[:'country_code']
      end

      if attributes.key?(:'admin_code')
        self.admin_code = attributes[:'admin_code']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'ascii_name')
        self.ascii_name = attributes[:'ascii_name']
      end

      if attributes.key?(:'level')
        self.level = attributes[:'level']
      end

      if attributes.key?(:'parent_geoname_id')
        self.parent_geoname_id = attributes[:'parent_geoname_id']
      end

      if attributes.key?(:'population')
        self.population = attributes[:'population']
      end

      if attributes.key?(:'latitude')
        self.latitude = attributes[:'latitude']
      end

      if attributes.key?(:'longitude')
        self.longitude = attributes[:'longitude']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'geometry')
        self.geometry = attributes[:'geometry']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          geoname_id == o.geoname_id &&
          country_code == o.country_code &&
          admin_code == o.admin_code &&
          name == o.name &&
          ascii_name == o.ascii_name &&
          level == o.level &&
          parent_geoname_id == o.parent_geoname_id &&
          population == o.population &&
          latitude == o.latitude &&
          longitude == o.longitude &&
          country == o.country &&
          geometry == o.geometry
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, geoname_id, country_code, admin_code, name, ascii_name, level, parent_geoname_id, population, latitude, longitude, country, geometry].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
