=begin
#GeoAPI

#Geographic data REST API — modern replacement for GeoNames.  Serves countries, regions, cities, postal codes, timezones, and IP geolocation data through a fast, well-documented JSON API with cursor-based pagination and field selection.  ## Authentication All endpoints (except health check) require an API key passed via the `X-API-Key` header.  ## Rate Limiting Two independent limits apply to every authenticated request: a per-second throttle and a monthly quota. They fail with different error codes because they call for different client behaviour — `rate_limit_exceeded` means back off for a moment, `quota_exceeded` means the plan's monthly allowance is exhausted until the period resets.  Responses include rate limit headers: - `X-RateLimit-Limit` — requests per second allowed - `X-RateLimit-Remaining` — requests remaining in current window - `X-RateLimit-Reset` — **Unix epoch second** at which the applicable limit   resets. This is an absolute timestamp, not a duration. On a   `quota_exceeded` response it carries the end of the monthly quota period   rather than the next second boundary. - `X-Monthly-RateLimit-Limit` — monthly quota - `X-Monthly-RateLimit-Remaining` — monthly requests remaining - `X-RateLimit-Upgrade` — advisory message, present only once monthly usage   passes 80% of the plan's quota - `Retry-After` — seconds to wait before retrying. Present on both 429s and   the unambiguous duration; prefer it over deriving one from   `X-RateLimit-Reset`.  ## Pagination List endpoints use cursor-based pagination with `cursor` and `limit` parameters. Maximum limit is 100. Responses include pagination metadata in the `meta` object.  ## Field Selection Use `?fields=name,population` on any endpoint to receive only the specified fields. 

The version of the OpenAPI document: 1.2.0

Generated by: https://openapi-generator.tech
Generator version: 7.21.0

=end

require 'date'
require 'time'

module GeoAPI
  class Country < ApiModelBase
    attr_accessor :id

    attr_accessor :geoname_id

    attr_accessor :iso_code

    attr_accessor :iso3_code

    attr_accessor :iso_numeric

    attr_accessor :fips_code

    attr_accessor :name

    attr_accessor :capital

    attr_accessor :area_sq_km

    attr_accessor :population

    attr_accessor :continent_code

    attr_accessor :tld

    attr_accessor :currency_code

    attr_accessor :currency_name

    attr_accessor :phone

    attr_accessor :postal_code_format

    attr_accessor :postal_code_regex

    attr_accessor :languages

    attr_accessor :neighbours

    attr_accessor :latitude

    attr_accessor :longitude

    attr_accessor :flag_emoji

    # Country boundary. Returned by default on `GET /v1/countries/{code}` and on request via `?fields=geometry` on `GET /v1/countries`.  NOT TIER-GATED. Country geometry is served on every plan, including Free. Region geometry is gated — see the `Region` schema.
    attr_accessor :geometry

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'geoname_id' => :'geoname_id',
        :'iso_code' => :'iso_code',
        :'iso3_code' => :'iso3_code',
        :'iso_numeric' => :'iso_numeric',
        :'fips_code' => :'fips_code',
        :'name' => :'name',
        :'capital' => :'capital',
        :'area_sq_km' => :'area_sq_km',
        :'population' => :'population',
        :'continent_code' => :'continent_code',
        :'tld' => :'tld',
        :'currency_code' => :'currency_code',
        :'currency_name' => :'currency_name',
        :'phone' => :'phone',
        :'postal_code_format' => :'postal_code_format',
        :'postal_code_regex' => :'postal_code_regex',
        :'languages' => :'languages',
        :'neighbours' => :'neighbours',
        :'latitude' => :'latitude',
        :'longitude' => :'longitude',
        :'flag_emoji' => :'flag_emoji',
        :'geometry' => :'geometry'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'geoname_id' => :'Integer',
        :'iso_code' => :'String',
        :'iso3_code' => :'String',
        :'iso_numeric' => :'Integer',
        :'fips_code' => :'String',
        :'name' => :'String',
        :'capital' => :'String',
        :'area_sq_km' => :'Float',
        :'population' => :'Integer',
        :'continent_code' => :'String',
        :'tld' => :'String',
        :'currency_code' => :'String',
        :'currency_name' => :'String',
        :'phone' => :'String',
        :'postal_code_format' => :'String',
        :'postal_code_regex' => :'String',
        :'languages' => :'Array<String>',
        :'neighbours' => :'Array<String>',
        :'latitude' => :'Float',
        :'longitude' => :'Float',
        :'flag_emoji' => :'String',
        :'geometry' => :'GeoJSONMultiPolygon'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `GeoAPI::Country` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `GeoAPI::Country`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'geoname_id')
        self.geoname_id = attributes[:'geoname_id']
      end

      if attributes.key?(:'iso_code')
        self.iso_code = attributes[:'iso_code']
      end

      if attributes.key?(:'iso3_code')
        self.iso3_code = attributes[:'iso3_code']
      end

      if attributes.key?(:'iso_numeric')
        self.iso_numeric = attributes[:'iso_numeric']
      end

      if attributes.key?(:'fips_code')
        self.fips_code = attributes[:'fips_code']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'capital')
        self.capital = attributes[:'capital']
      end

      if attributes.key?(:'area_sq_km')
        self.area_sq_km = attributes[:'area_sq_km']
      end

      if attributes.key?(:'population')
        self.population = attributes[:'population']
      end

      if attributes.key?(:'continent_code')
        self.continent_code = attributes[:'continent_code']
      end

      if attributes.key?(:'tld')
        self.tld = attributes[:'tld']
      end

      if attributes.key?(:'currency_code')
        self.currency_code = attributes[:'currency_code']
      end

      if attributes.key?(:'currency_name')
        self.currency_name = attributes[:'currency_name']
      end

      if attributes.key?(:'phone')
        self.phone = attributes[:'phone']
      end

      if attributes.key?(:'postal_code_format')
        self.postal_code_format = attributes[:'postal_code_format']
      end

      if attributes.key?(:'postal_code_regex')
        self.postal_code_regex = attributes[:'postal_code_regex']
      end

      if attributes.key?(:'languages')
        if (value = attributes[:'languages']).is_a?(Array)
          self.languages = value
        end
      end

      if attributes.key?(:'neighbours')
        if (value = attributes[:'neighbours']).is_a?(Array)
          self.neighbours = value
        end
      end

      if attributes.key?(:'latitude')
        self.latitude = attributes[:'latitude']
      end

      if attributes.key?(:'longitude')
        self.longitude = attributes[:'longitude']
      end

      if attributes.key?(:'flag_emoji')
        self.flag_emoji = attributes[:'flag_emoji']
      end

      if attributes.key?(:'geometry')
        self.geometry = attributes[:'geometry']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          geoname_id == o.geoname_id &&
          iso_code == o.iso_code &&
          iso3_code == o.iso3_code &&
          iso_numeric == o.iso_numeric &&
          fips_code == o.fips_code &&
          name == o.name &&
          capital == o.capital &&
          area_sq_km == o.area_sq_km &&
          population == o.population &&
          continent_code == o.continent_code &&
          tld == o.tld &&
          currency_code == o.currency_code &&
          currency_name == o.currency_name &&
          phone == o.phone &&
          postal_code_format == o.postal_code_format &&
          postal_code_regex == o.postal_code_regex &&
          languages == o.languages &&
          neighbours == o.neighbours &&
          latitude == o.latitude &&
          longitude == o.longitude &&
          flag_emoji == o.flag_emoji &&
          geometry == o.geometry
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, geoname_id, iso_code, iso3_code, iso_numeric, fips_code, name, capital, area_sq_km, population, continent_code, tld, currency_code, currency_name, phone, postal_code_format, postal_code_regex, languages, neighbours, latitude, longitude, flag_emoji, geometry].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
